name: Java Maven Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Use Java Maven Workflow Template
      uses: Shanridhu/github-action-maven-example-start@master
      with:
        workflow_path: .github/workflows/workflow2.yml
